### ISSUE TITLE
Will Facebooker support "like"?

### ISSUE THREAD

**Issue by PttCodingMan** [gpwork4u/Facebooker#3]
As title,
I read the doc, but I did not fine how to like a post.
Will Facebooker support "like"?

Thank you.

**Comment by gpwork4u** [comment]
Yes, I am working on it.

**Comment by gpwork4u** [comment]
Done.
You can use like_post now. 
Please update Facebooker to v0.1.0.
The detail is written in doc.md.

Thanks.
